// <auto-generated />
using KilnLog.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KilnLog.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20240911000000_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("KilnLog.Api.Models.FiringSchedule", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("ConeOrTarget").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<int>("KilnId").HasColumnType("integer");
            b.Property<string>("Name").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.HasKey("Id");
            b.HasIndex("KilnId");
            b.ToTable("FiringSchedules");
        });

        modelBuilder.Entity("KilnLog.Api.Models.Kiln", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("FuelType").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.Property<string>("KilnCode").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<int>("MaxTempC").HasColumnType("integer");
            b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.Property<int>("StudioId").HasColumnType("integer");
            b.HasKey("Id");
            b.HasIndex("StudioId", "KilnCode").IsUnique();
            b.ToTable("Kilns");
        });

        modelBuilder.Entity("KilnLog.Api.Models.LoadBatch", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("GlazeNotes").HasColumnType("text");
            b.Property<int>("KilnId").HasColumnType("integer");
            b.Property<DateOnly>("LoadDate").HasColumnType("date");
            b.Property<int>("PieceCount").HasColumnType("integer");
            b.Property<int>("ScheduleId").HasColumnType("integer");
            b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.HasKey("Id");
            b.HasIndex("KilnId");
            b.HasIndex("ScheduleId");
            b.ToTable("LoadBatches");
        });

        modelBuilder.Entity("KilnLog.Api.Models.ScheduleSegment", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<int>("HoldMinutes").HasColumnType("integer");
            b.Property<decimal>("RampCPerHour").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
            b.Property<int>("ScheduleId").HasColumnType("integer");
            b.Property<int>("Seq").HasColumnType("integer");
            b.Property<int>("TargetTempC").HasColumnType("integer");
            b.HasKey("Id");
            b.HasIndex("ScheduleId", "Seq").IsUnique();
            b.ToTable("ScheduleSegments");
        });

        modelBuilder.Entity("KilnLog.Api.Models.Studio", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("City").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<string>("Name").IsRequired().HasMaxLength(128).HasColumnType("character varying(128)");
            b.Property<string>("Notes").HasColumnType("text");
            b.HasKey("Id");
            b.ToTable("Studios");
        });

        modelBuilder.Entity("KilnLog.Api.Models.User", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
            b.Property<string>("Role").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
            b.Property<string>("Username").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.HasKey("Id");
            b.HasIndex("Username").IsUnique();
            b.ToTable("Users");
        });

        modelBuilder.Entity("KilnLog.Api.Models.FiringSchedule", b =>
        {
            b.HasOne("KilnLog.Api.Models.Kiln", "Kiln")
                .WithMany("Schedules")
                .HasForeignKey("KilnId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Kiln");
        });

        modelBuilder.Entity("KilnLog.Api.Models.Kiln", b =>
        {
            b.HasOne("KilnLog.Api.Models.Studio", "Studio")
                .WithMany("Kilns")
                .HasForeignKey("StudioId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Studio");
        });

        modelBuilder.Entity("KilnLog.Api.Models.LoadBatch", b =>
        {
            b.HasOne("KilnLog.Api.Models.Kiln", "Kiln")
                .WithMany("LoadBatches")
                .HasForeignKey("KilnId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
            b.HasOne("KilnLog.Api.Models.FiringSchedule", "Schedule")
                .WithMany("LoadBatches")
                .HasForeignKey("ScheduleId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
            b.Navigation("Kiln");
            b.Navigation("Schedule");
        });

        modelBuilder.Entity("KilnLog.Api.Models.ScheduleSegment", b =>
        {
            b.HasOne("KilnLog.Api.Models.FiringSchedule", "Schedule")
                .WithMany("Segments")
                .HasForeignKey("ScheduleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Schedule");
        });

        modelBuilder.Entity("KilnLog.Api.Models.FiringSchedule", b =>
        {
            b.Navigation("LoadBatches");
            b.Navigation("Segments");
        });

        modelBuilder.Entity("KilnLog.Api.Models.Kiln", b =>
        {
            b.Navigation("LoadBatches");
            b.Navigation("Schedules");
        });

        modelBuilder.Entity("KilnLog.Api.Models.Studio", b =>
        {
            b.Navigation("Kilns");
        });
#pragma warning restore 612, 618
    }
}
